import type { Metadata } from "next";
import "./globals.css";
import { CsvProvider } from '../context/CsvContext';
import { ClerkProvider } from "@clerk/nextjs";
import NavBar from "@/components/NavBar";
import Onboarding from "./Onboarding/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignOutUrl={'/Onboarding'}>
      <CsvProvider>
      <html lang="en">
          <body>
            <NavBar/>
            <main>

            {children}
            </main>
          </body>
      </html>
        </CsvProvider>
    </ClerkProvider>
    
  );
}
